@default:
    just --list
    
@test:
    cargo build --release --target wasm32-unknown-unknown
    cp target/wasm32-unknown-unknown/release/typed_test.wasm src-typst/typed_test.wasm
    typst compile --root .. src-typst/test.typ
