[package]
name = "typwire"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["Tim Voßhenrich <@T1mVo>"]
license = "MIT OR Apache-2.0"
description = "Typed data exchange for Typst plugins."
repository = "https://github.com/T1mVo/typwire"
keywords = ["typing", "wasm", "plugin"]
categories = ["utility", "integration"]
compiler = "0.15.0"
